version: "3"
services:
  my_express:
    depends_on: 
      - my_mongo
    image: zavierjack1/express:latest
    ports:
      - "8080:8080"
    working_dir: /NodeJS-Express
    volumes: 
      - ../NodeJS-Express:/NodeJS-Express
    networks:
      - backend
  my_mongo: 
    image: zavierjack1/mean_course_mongo:latest
    ports: 
      - "27020:27017"
    env_file:
      - ./Mongo/.env
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes: 
      - mongodb_data:/data/db
    networks:
      - backend
volumes: 
  mongodb_data:
networks: 
  backend:
