version: "3"
services:
  my_angular:
    image: zavierjack1/mean_course_angular:latest
    ports:
      - "8085:8080"
    command: ng serve --host 0.0.0.0 --port 8080 --configuration local
    volumes: 
      - ../AngularApp:/AngularApp
  my_express:
    depends_on: 
      - my_mongo
    image: zavierjack1/mean_course_express:latest
    ports:
      - "8080:8080"
    volumes: 
      - ../NodeJS-Express:/NodeJS-Express
    networks:
      - backend
  my_mongo: 
    image: zavierjack1/mean_course_mongo:latest
    ports: 
      - "27020:27017"
    env_file:
      - .env
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes: 
      - mongodb_data:/data/db
    networks:
      - backend
volumes: 
  mongodb_data: